### ISSUE TITLE
Export ExplorerService as public API

### ISSUE THREAD

**Issue by 0b3r** [nestjs/cqrs#460]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

ExplorerService is not being exported as a public API

## Expected behavior

ExplorerService is a part of the publicly accessible API

## What is the motivation / use case for changing the behavior?

I would like to use the ExplorerService as a part of a custom CQRS module.

**Comment by kamilmysliwiec** [comment]
`ExplorerService` is considered as a private API, which doesn't necessarily make it inaccessible. The fact that it isn't exported from the `index` file means that you very likely shouldn't use it in your app **unless** you have a good understanding of the internals of this module. I'm assuming that you do have it since you are in fact creating a custom CQRS module, and in this case, you can safely use a nested import.

**Comment by RobertLowe** [comment]
@kamilmysliwiec can you define what you mean by a "Nested import"?
