### ISSUE TITLE
How to handle error with saga?

### ISSUE THREAD

**Issue by fireridlle** [nestjs/cqrs#534]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

For example controller call service, service executes a command. command publish event, saga listens for event, and execute another command. the last command throws an error. did i miss documentation on how to return an error via http response that comes from the controller?

## Current behavior
Error is not shown as http response

## Expected behavior
Error is shown as http response

**Comment by underfisk** [comment]
You can use a global Catch to handle RpcError or general error and you can check the context and see if you have http available to return a custom http error message
In fact there's nothing in the documentation because it seems "trivial" for long-time nestjs users but basically, you can check the exception type and handle. Also if you invoke your command directly in the controller method, you can use a try/catch and handle it (if your execute method throws an error inside, then your high level try/catch will catch it)
Not sure if any one this helps but i also think that having this on the documentation would be helpful for new users (if you mind, just open an issue on the nestjs documentation project)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
