### ISSUE TITLE
Command handler dependency injection scope

### ISSUE THREAD

**Issue by wergimity** [nestjs/cqrs#60]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Command handler dependencies are being injected on module init. But since NestJS v6 there are provider scopes. And currently it's not possible to get request object in command handler.

## Expected behavior

Command handlers should be using dependency injection container when executing commands. And not when command handlers are being registered.

## Minimal reproduction of the problem with instructions

```
@CommandHandler(Test)
export class TestHandler implements ICommandHandler<Test> {
  @Inject(REQUEST)
  private request!: Request;

  public async execute(command: Test): Promise<any> {
    console.log(this.request); // undefined
  }
}
```

## Environment

<pre><code>
Nest version: 6.0.4

 
For Tooling issues:
- Node version: v10.15.0  
- Platform: Linux 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
So basically, the problem is that every `CqrsModule` provider is statically scoped which mean that they cannot depend on request-scoped providers. Once you define your command handler as a request-scoped provider, either `CommandBus` or `QueryBus` won't be able to reference it. This is not an issue, but rather a design decision that sits behind the entire module.

**Comment by grexlort** [comment]
Same problem here, were using request-scope for multi-tenancy (per tenant database connection injection) and CQRS module in this case will not work for us?

**Comment by xdave** [comment]
@grexlort @kamilmysliwiec started using https://www.npmjs.com/package/express-http-context for this.  Uses something called "continuation-local storage" (kind of like thread-local storage, but for nodejs) to keep track of some state during a request.

I configure AppModule to (configure(consumer) { consumer.apply(...).forRoutes('*') }):
1.  Load express-http-context middleware
2. Load my middleware that selects the tenant and sets the http context for that tenant
3. Connect to database, etc

Then you can just pull in http context anywhere else in your app and grab the state.  It's stored in the current 'continuation'.

**Comment by cuongphamcxa** [comment]
@kamilmysliwiec: Could we support the request-scoped for command handler ? Our logging service is request-scoped, so can't use in in command handler :((

**Comment by kamilmysliwiec** [comment]
Let me reopen this. I'll think about what we can do as soon as I find a bit more time.

**Comment by cuongphamcxa** [comment]
@kamilmysliwiec : Thank for you quick response. I'm a big fan of NestJs 👍

**Comment by juicycleff** [comment]
Willing to work on this if @kamilmysliwiec thinks the design can be altered without too much performance issue

**Comment by cuongphamcxa** [comment]
@kamilmysliwiec: Is there any official way to resolve/get the instance by scope defined ?
I try to resolve my handler using `ModuleRef` but it require a contextId. I'm enable to resolve the handler instance by passing an `undefined` contextId but I can't inject the `REQUEST` into the handler.

**Comment by vinzcoco** [comment]
Hello @kamilmysliwiec thanks for your job on Nestjs.
Do you have a workaround to this problem?

**Comment by unckleg** [comment]
Any updates ? Thanks!

**Comment by shuramita** [comment]
waiting for solution. thanks!

**Comment by xdave** [comment]
In order for this to work, each command, query, and event handler would have to somehow know what request initiated it after a long running process (for example) even long after the controller has returned and the request is complete. This would require attaching that context to each command, query, and event or at least a request id that it can lookup later.

It seems like most people in the cqrs/es community tend to do this manually in the .NET world by just passing around a context object with some correlation identifiers and other useful info like what user initiated the request, a correlationId, timestamp, etc

**Comment by xdave** [comment]
What I'm thinking about doing is creating a custom parameter decorator with this info and then having another parameter on all of my command, query, and event constructors that takes this context. It would run, theoretically, after the middleware, interceptors, and guards to capture things like tenant db selection, auth, creating a correlationId, etc. Then I would store this context inside of all of the events that are persisted so that a long running, distributed transaction can complete properly.

**Comment by shajeeck** [comment]
@kamilmysliwiec Any updates ? Thanks!

**Comment by xdave** [comment]
@rafaelkallis This is awesome!  What kind of effort do you think it take to refactor the existing busses (QueryBus, CommandBus, EventBus) to make it work like this and create a pull request?

If we could quantify the work, I might actually volunteer to help if @kamilmysliwiec  thinks this is a good way forward on this issue.

Not sure what kind of 3rd party pkgs that depend on the current behavior would be impacted, either.  Any insight is welcome :)

**Comment by rafaelkallis** [comment]
@xdave I am considering creating a library that exposes an abstract mediator (command bus) class, so that clients can create reusable concrete mediators. I am sure there are codebases beyond the cqrs module that could benefit from this. In fact this pattern is popular in other language stacks (most notably https://github.com/jbogard/MediatR).

In the context of `@nestjs/cqrs`, the `CommandBus` and `QueryBys` would be concrete implementations of this abstract mediator class. 

We can start like this and if it is useful to nestjs, it can be absorbed by them, happy to maintain the codebase as well to be honest.

**Comment by xdave** [comment]
I think figuring out how events and sagas fit into this would be helpful.  While it would be useful to have 1:n request-scoped event handlers, it's probably not possible to scope them by request due to the nature of how the pattern works.

**Comment by rafaelkallis** [comment]
Event handlers shouldn't be a problem either, they are also part of mediatR actually, under the name "notifications" (https://github.com/jbogard/MediatR/wiki#notifications). I also assume sagas are easy to manage since they also make use of decorators.

**Comment by xdave** [comment]
@rafaelkallis I guess it wouldn't limit us, just curious to see what happens if a normally request-scoped command is executed by a saga or event handler outside of the request pipeline.

**Comment by rafaelkallis** [comment]
@xdave the answer is very simple: the mediator is request-scoped, therefore any mediator client becomes request-scoped :) so I can imagine sagas will also become request-scoped.

**Comment by xdave** [comment]
The problem with this is that any provider that is request scoped is automatically garbage collected after the request is complete.

This prevents the Mediator from running continuously in the background to listen for incoming events that may be triggered by outside forces, timers, or from code that is being executed *outside* of the entire request pipeline.

This becomes a real problem if I want to have an Observable bus.  The Observable, being tied to a request-scoped provider, will only live as long as that instance of Mediator exists.  In order for the Observable stream to remain open across *all* requests, it will be locked-in to the request context of the first request that created it *until* that Observable is "completed" (stream end).

Any new requests that come in while that instance still exists will create new Observables instead of using the first one.

**Comment by xdave** [comment]
Quite frankly, I'm OK with that, but I'm still not sure having request-scope event/notification listeners is going to be useful.

**Comment by rafaelkallis** [comment]
> This prevents the Mediator from running continuously in the background to listen for incoming events that may be triggered by outside forces, timers, or from code that is being executed outside of the entire request pipeline.

Correct, but perhaps we could get around this by modifying the mediator implementation to detect the scope and adjust the handler resolution strategy accordingly (e.g., `this.httpRequest === null` implies scope is singleton, therefore use `moduleRef.get(Foo)` instead of `resolve()` ?). I am not sure I like doing this, instead I would prefer the framework would provide a `Scoped` scope (like in .Net), or custom scopes, so that there can exist other short-lived transactional scopes other than request scopes.

> This becomes a real problem if I want to have an Observable bus. The Observable, being tied to a request-scoped provider, will only live as long as that instance of Mediator exists. In order for the Observable stream to remain open across all requests, it will be locked-in to the request context of the first request that created it until that Observable is "completed" (stream end).

I imagine there is a new "observable bus" (and subscriptions) for each incoming request.

**Comment by xdave** [comment]
What I did in my test yesterday was catch InvalidClassScopeException for `resolve()` and then use `get()` in the catch block.  This prevents you from having to explicitly use `{ scope: Scope.REQUEST }` on the Handlers.  As for custom scopes, this is a question for @kamilmysliwiec -- would be nice to get an idea what he thinks of all of this. :)

**Comment by rafaelkallis** [comment]
some more thoughts:

> custom scopes
A low level api for custom scopes exists actually. `ContextIdFactory.create()` is the fundamental building block for custom scopes, one only has to provide an abstraction for it that makes sense for a use case.

What smells to me is that the mediator has knowledge about a request, and needs that request to resolve other services in a scope subtree. Perhaps having an abstraction over `moduleRef` that allows clients to resolve services in a subtree without supplying a contextId would allow for a more elegant solution. A `resolve()` without a `contextId`.

**Comment by xdave** [comment]
Seems like such an abstraction exists could be further extended, ie. ExecutionContext?

**Comment by rafaelkallis** [comment]
No, ExecutionContext is not an abstraction over moduleRef. Let me illustrate with an example:

```ts
// scope abstraction, can originate from requests, timers, cron, amqp consumers, etc.
@Injectable()
class Scope {
  // wraps contextId ?
}

// moduleRef abstraction, service locator pattern, has no knowledge about its scope
@Injectable()
class ServiceLocator {
  private readonly scope: Scope;
  constructor(scope: Scope) {
    this.scope = scope;
  }
  
  // locate service from current scope, implementation unknown
  getService<T>(typeOrToken: Type<T> | string | symbol): Promise<T>;
}

// has no knowledge about its scope
@Injectable()
class Mediator {
  private readonly serviceLocator: ServiceLocator;
  constructor(serviceLocator: ServiceLocator) {
    this.serviceLocator = serviceLocator;
  }
  
  async send(request) {
    const handlerType = getRequestHandlerType(request);
    // is it request scoped? is it singleton? Mediator doesn't know
    const handler = await this.serviceLocator.getService(handlerType);
    return await handler.handle(request);
  }
}
```

So with such an abstraction we can address the mediator not having to worry about scope. The implementation you have suggested (try catch) is a candidate solution, but preferably we use an alternative that does not rely on try catch for control flow.

**Comment by xdave** [comment]
@rafaelkallis I like this idea.

**Comment by rafaelkallis** [comment]
I implemented the following locally and having no problems so far:

```ts
@Injectable()
export class ServiceLocator {
  private readonly moduleRef: ModuleRef;
  private readonly contextId: ContextId;

  public constructor(moduleRef: ModuleRef, @Inject(REQUEST) request: Request) {
    this.moduleRef = moduleRef;
    this.contextId = ContextIdFactory.getByRequest(request);
  }

  public async getService<T>(type: Abstract<T> | Type<T>): Promise<T> {
    return this.moduleRef.resolve(type as any, this.contextId, {
      strict: false,
    });
  }
}
```

Note that it lives in the request scope (works for my mediator use case)

**Comment by xdave** [comment]
FYI you can avoid manually assigning variables in the constructor with the following...

Plus all class properties & methods are public by default, there's no need for the `public` visibility specifier.

```ts
@Injectable()
export class ServiceLocator {
 constructor(
    private readonly moduleRef: ModuleRef,
    @Inject(REQUEST) private readonly request: Request,
) { }

 async getService<T>(type: Abstract<T> | Type<T>): Promise<T> {
    return this.moduleRef.resolve(type as any, this.contextId, {
      strict: false,
    });
  }
}
```

**Comment by xdave** [comment]
So, how do I make this work for 1:n event handlers?

**Comment by rafaelkallis** [comment]
based on earlier code:
```ts
@Injectable()
export class Mediator {

  public async publish<TNotification extends Notification>(notification: TNotification): Promise<void> {
    const notificationType = notification.constructor as Type<TNotification>;
    const notificationHandlerTypes = getNotificationHandlerTypes(notificationType);
    for (const notificationHandlerType of notificationHandlerTypes) {
      const handler = await this.serviceLocation.getService(notificationHandlerType);
      await handler.handle(notification);
    }
  }
}
```

`getNotificationHandlerTypes()` is left as exercise for the reader ;) (read my previous posts to get an idea of how it looks like)

**Comment by diego-rangel** [comment]
@kamilmysliwiec Any updates ? Thanks!

**Comment by xdave** [comment]
So, I started using the @nestjs/microservices package instead of this package to get what I want.

- The controllers of the microservice can serve the same purpose as Command/Query handlers -- they are (by design) 
request-scoped.
- I have a wrapper class around client proxy that copies request-context-like stuff to each Command/Query
- The AggregateRoot domain models have mutation methods that accept a "reason" parameter, which is the Command of the mutation.  This contains all of the request context which apply() then copies to events before they're published (ie. emitted using the client proxy).
- Repositories pull the events directly out of the Aggregate Root using getUncommittedEvents() and publish from there
- I had to re-implement the Sagas functionality from @nestjs/cqrs so that I can fan-out events inside of each service and make them send commands using the client proxy -- allowing me to also copy request context to the resulting commands from the events -- thereby establishing a complete audit chain for any given series of related operations. 

It was a lot to figure out, but it's way cleaner and I never have a static/request/transient injection problem now.

**Comment by lukaszwilisowski** [comment]
@xdave can you share the code for the solution you just described? 
I am thinking about advantages / drawbacks of this approach compared to custom cqrs based on RxJS and Mediator pattern (@rafaelkallis approach). 

@kamilmysliwiec can you shortly describe the rationale for making CQRS handlers singleton-scoped?  

Current cqrs module in nest.js is great, but has its limitations. My initial conclusions are the following:
1. You cannot inject request-scoped dependencies into handlers.  What you can do instead is to inject them in a controller and then pass them onto the handler. 

For example: to get currently authenticated user from DB - instead of this:
```typescript
  @Get('current')
  async getCurrentUser(): Promise<IUser> {
    return this.queryBus.execute(new GetCurrentUserQuery());
  }
```
you can do this:
```typescript
  @Get('current')
  async getCurrentUser(@CurrentUser() user: ICurrentUser): Promise<IUser> {
    return this.queryBus.execute(new GetUserByIdQuery(user.id));
  }
```

The downsides of this are redundancy and lesser security. If you want to prevent developers from making simple mistakes, you would like to differentiate between functions invoked in current-user-context vs administrative-context. It is generally better to inject context into handler directly (final execution point).

2. As far as I understand you cannot add guards to CQRS and queries handlers. This would be useful because some queries call other queries and granular approach to security is much safer. The workaround is to use standard controller guards, but we lose modularity features (other modules can extend functionality of existing routes), leading to higher redundancy.  

3. You cannot easily extend the logic of commandBus and queryBus. It would be nice to have general commandHandler and queryHandler that can be decorated the same way as I commented here: https://github.com/nestjs/nest/issues/4786. This would form a nice abstraction layer: to be able to add custom logging / authentication / other logic to all handlers (but not controllers). Unless I am missing something, in which case feel free to correct me. 

So now I am more inclined to try the microservice architecture (although it seems a little bit far-fetched for my requirements) and if not, consider reimplementing the whole CQRS module.  

Let me know what you think.

**Comment by xdave** [comment]
@lukaszwilisowski I ended up re-implementing/adding everything I needed from the CqrsModule:
- ICommand, IQuery, IEvent, ICommandHandler, IQueryHandler 
- AggregateRoot
- Saga processing

I may not have needed to do this, but I wanted to customize things a lot further than you generally can with the CqrsModule.  I add things like:
- `hostname`,
- `clientIp`,
- `correlationId`,
- `causationId`, and
- `timestamp`

to each Command, Query, and Event as they're created, because my use cases require it for things like multi-tenancy and auditing.  The saga processor needed to be re-implemented to handle copying the request context stuff over to the commands, to maintain the audit trail.

I'll try to get some example code pushed up soon somewhere that demonstrates how it all works.

**Comment by xdave** [comment]
With the above (if it is split out into multiple services), it should be possible to do things like:
- verify an JWT using another service in an API Guard
- attach the current userId to the Request Context
- forward the context (ie, the command/query) to the respective service it's for
- use an interceptor to query the user by id and attach it to the RCP Context
- pull it in using a decorator directly on the ICommandHandler

**Comment by lukaszwilisowski** [comment]
Thanks, I will check it out and let you know my thoughts.

**Comment by Farenheith** [comment]
@kamilmysliwiec I'm also in need of such feature for the command handler and, regardless I could do some workarounds to achieve what I needed, I thought that would be nice for the command bus to support request scoped handlers.

So, I forked the repo and tried to change it myself.
https://github.com/nestjs/cqrs/compare/master...Codibre:master

The solution already worked locally :)
As soon as I get some time I'll complete the change with unit tests and send a PR for the project!

In the meantime, with anyone can take a look at the change to give some opinions it'd greatly help me with my anxiety lol

**Comment by pedrosodre** [comment]
I'm working together with @Farenheith on the changes to accept handlers with request scope, I think it should be ready soon :)

**Comment by koolamusic** [comment]
@pedrosodre thanks for taking this up, really appreciated.

**Comment by xdave** [comment]
@Farenheith @pedrosodre excellent!

**Comment by xdave** [comment]
@Farenheith @pedrosodre OK, if I put `{ command: SomeCommand,  scope: Scope.REQUEST }` in the `@CommandHandler()` decorator, the dependencies resolve, but I cannot `@Inject(REQUEST)` in the same class -- the request object is undefined.

**Comment by Farenheith** [comment]
@xdave thanks for taking your time to test our try!
I added some unit test just to assure the request scope and singleton injection for handlers, and everything is working as we expected!
You can take a look at the tests in the **command-bus.spec.ts** and **query-bus.spec.ts** files, but I can already say to you that there are three ways to inject a request scope handler that I know of:

* Through provider specification:
Take the handler
```ts
@QueryHandler(MyQuery)
class MyHandler implements IQueryHandler<MyQuery> {
... some code ...
}
```
And the provider:
```ts
{
  provide: MyHandler,
  useClass: MyHandler,
  scope: Scope.REQUEST,
}
```
* Through Injectable decorator:
```ts
@QueryHandler(MyQuery)
@Injectable({ scope: Scope.REQUEST })
class MyHandler implements IQueryHandler<MyQuery> {
... some code ...
}
```
* Through CommandHandler/QueryHandler/EventHandler decorator, that @pedrosodre coded in our fork:
```ts
@QueryHandler({ command: MyQuery, scope: Scope.REQUEST })
class MyHandler implements IQueryHandler<MyQuery> {
... some code ...
}
```

I let some example running in the tests I talked above the three options , you can take a look :)
About the request scope object injected in the handler, the only scenario I found where this is a problem is when the Handler is singleton, but I think this is an expected behavior. Have you tested these scenarios in our fork? If so, Take a look at the tests to see if there is something different from what you tried out and let me know.

**Comment by xdave** [comment]
@Farenheith hi, thanks for the update. I have pulled the latest from that fork, and I am still having the same problem. The request is undefined when injected into the handler.

**Comment by Farenheith** [comment]
@xdave I need to see your code to understand what the problem is. Could you upload a repo in github simulating the issue?

**Comment by xdave** [comment]
@Farenheith Here's a repo that demonstrates the problem: https://github.com/xdave/test-scoped-cqrs
I have installed your fork by cloning it into a separate directory, and running: `npm link ../cqrs @nestjs/cqrs` in this repo dir.

**Comment by Farenheith** [comment]
@xdave nice, I'll try it right away. Thank you

**Comment by Farenheith** [comment]
@xdave now I understood what you meant, sorry.
Unfortunately for this to work, the controller and the command bus must be request scoped as well, but what @pedrosodre and I designed keeps the bus singleton.

I think the idea of command bus is to totally decouple the business rule from the entry point, so, in our line of thought, it makes sense for the bus to be a singleton and the handler must not know the transporter details (in the case of your example, express.Request). However, the command bus can create scopes for each command execution through the resolving of a request-scoped handler.

So, to use it as you intend to, you may have a custom way to set the scoped information. Take a look at [this example](https://github.com/Farenheith/test-scoped-crqs) and tell me if you agree with it.
Regardless, I strongly recommend you to not use exactly the Request express reference into your business rule, but, instead, use some "metadata" information that the entry point must set in the command creation, in that way, you can keep a good decouple and use the same application logic for different entry points (for example, in the future you can use it as a GRPC entry point, or a scheduled execution, things that has nothing to do with express).

**Comment by xdave** [comment]
Manually passing request-related information along with the command/query is exactly what I wanted to avoid, and defeats the purpose (I think) of doing all of this.

I realize that I should be keeping "expressed-related" things out of my application, but I *need* to be able to access the request in order to keep track of context that has information FROM the request -- without littering my commands with that information.  For example, I need to keep track of the currently selected database in a multi-tenant situation, which means my repositories need to access that USING the request, which the Command handler depends on. 

May I suggest, that when you are injecting the handlers, check for REQUEST scope metadata and then do something like the following?:

```ts
// Pseudo code
let handlerInstance: ICommandHandler<ICommand>;
if (handlerIsRequestScoped) {
  const req = await moduleRef.resolve(REQUEST, undefined, { strict: false });
  const contextId = ContextIdFactory.getByRequest(req);
  handlerInstance = await moduleRef.resolve(HandlerType, contextId, { strict: false });
} else {
  handlerInstance = moduleRef.get(HandlerType, { strict: false });
}
```

**Comment by Farenheith** [comment]
@xdave It can't be done unless the commandBus is request scoped, otherwise it'll not have access to the REQUEST that a request scoped controlled received, and we really disagree on that point.
The idea of a request scoped bus may create a heavy overload for each request and the handler must not have access to the express request directly.
To be honest, I realized with your question that our PR don't aim to solve the question made in this thread, but a need we had to have scoped request handlers. I'll remove from the PR to reference to this issue

**Comment by Farenheith** [comment]
@xdave I know you don't want to pollute your command with request information, but I really think that, in your case, it makes sense to put, not request, but multi-tenant information in it. Any information derived from the entry point transporter must be obtained in the entry point, and the command must have every request information necessary for the command execution.

Using what we're proposing to the nestjs team and having a request-scoped helper class, you can achieve access for multi-tenant information at every point of your application.
For example, with the following line
```ts
 async execute(command: SomethingCommand): Promise<any> {
    this.req.tenantId = command.tenantId;
    this.service.do(command.message);
  }
```

Assuming req is an instance of a request-scoped service and the handler is also request-scoped, you can guarantee access to the tenantId at every request-scoped service with it, without having to pass it through every method of your stack.

**Comment by Farenheith** [comment]
@xdave I had an idea of how to provide what you need.
Take a look at https://github.com/Farenheith/test-scoped-crqs.
The problem is that you'll be unable to test it through npm link due to the uniqueness of the internal @nestj/core REQUEST_CONTEXT_ID. So, you will need to copy the dist folder of the branch **request-command-bus** of our fork inside the folder node_modules/@nestjs/crqs.

**Comment by xdave** [comment]
I do not consider this to be a solution. I have projects with hundreds of commands and queries that do not pass extra information inside.

Instead, we use continuation local storage to keep track of request-specific information starting in middleware, and then used in places like repositories and analytics. It's a hack, but it works.  This keeps infrastructure-related details out of our application code. 

Additionally, I anticipate that this PR will not be merged upstream in its current form, because of two problems:

1. The contextId of the request itself is not being used to scope the providers,
2. It seems that you have removed usage of the command publisher inside of the command bus

I don't think there is a real solution to this until perhaps the registration of handlers is changed to be more dynamic. The Explorer service normally instantiates each handler in the Bootstrap phase, and this requires the busses to be static.

If the registration could occur separately from the busses, the busses could be provided in any scope (with the exception of the event bus).

Events are different, because the events may fire later, after a long running async process and after the request cycle is complete... so, scoping event handlers is not reasonably possible.  In this case, it is necessary to manually store some contextual information inside of the events. This can be done trivially by using a custom event publisher.

**Comment by xdave** [comment]
@Farenheith here's what I've come up with as a workaround using stock @nestjs/cqrs: https://github.com/xdave/test-scoped-cqrs

**Comment by Farenheith** [comment]
Actually I did not remove any usage of the publisher from the busses, I took a look at the untouched master and it appears that they're being used in the same places as before. About the contextId, maybe you're right.

The thing is that I see scoped handlers and the request itself as two different things. The request scope concept, in my understanding, refers to the request of a root object to the moduleRef (maybe because I came from inversify), and a scoped handler can make sense even for events when you see it that way. For example:
Assuming a scoped Handler, let's say you have an event/command/query that, when handled, a few classes are injected in the injection chain, with something like this:
![image](https://user-images.githubusercontent.com/5713887/105692828-b1e09180-5edd-11eb-9b43-3bf0acd46038.png)
Imagine that each class that uses the repository may query the same information, you don't want to do a new database roundtrip for each one, but you also don't want to cache it in a redis or something because others request must no use this cache. If your handler is scoped, it's quite simple to solve this: you just need to store the promise of the first call the repository got and respond it for the other ones. When the request ends, everything dies and you're good to go.
You may also want to collect different statistics information at many points of your chain to log it at the end of your request, again, with a scoped handler, you can just inject a collector at each point you want, collect it and log it all at once in the end. It's quite simple and quite decoupled to do so.

Even so, I see the value in your need and I did a transient command bus that would work for you, so I'd like for you take a look if you can (I think you didn't saw my last message). I didn't put it in the PR branch because I see it as a different problem from the one I was aiming at the beginning, as I realized, talking to you, that my need was similar but no the same of this issue and I misunderstood it at the beginning.

**Comment by xdave** [comment]
@Farenheith

First, I did notice that the use of the `ICommandPublisher` and `IQueryPublisher` are indeed missing -- see:
1. https://github.com/nestjs/cqrs/pull/549/files#diff-ba3b51a6452723e5c5932802cf32882082f3f0c0acbae54cd4e9f3ae4e5314b6L44
2. https://github.com/nestjs/cqrs/pull/549/files#diff-077f9c78eb3526c090ed295ae929fd52c7a9348c6b858566daafab0dc2bc70e3L51

Second, I like the idea of the Transient bus, this does give the desired effect.  A common pattern in (private) projects I maintain is (simplified version):

Nest starts-up/boostrap -> Master DB Connection established, and at some point later...

A GET/POST/PUT, etc request is received:
  -> Tenant lookup/selection from Master DB using Request information -> Establish Tenant DB Connection
  -> Command/Query -> Handler -> Repository uses Tenant DB to read/write data

The Transient Bus indeed makes this work.

**Comment by Farenheith** [comment]
@xdate, man, I really not see where there is this missing Publisher you're pointing out. Every reference to publish, publishAll and the Publishers are identical.
About the name TransientCommandBus I think you're right I changed it.
But thank you for your feedback :). Let's hope the nestjs team take a look in the PR @pedrosodre and I did and, if they accept it (with fix requests or not), then the idea of a request scope command bus can also be implemented. Or maybe they think in a better solution.

**Comment by xdave** [comment]
The call to this.subject$.next() is missing in execute()

**Comment by xdave** [comment]
@Farenheith  See the lines I highlighted in the links above.

**Comment by Farenheith** [comment]
@xdave thank you, now I saw it! :D It's nice for you to notice it. I'll fix it right away

**Comment by altick** [comment]
When could we expect this to be merged? I'm already using the fork and it's working pretty well. Btw thank you @Farenheith and @xdave for the great job!

**Comment by pedrosodre** [comment]
Would be cool if you can take a look on it @kamilmysliwiec :)

**Comment by viniciuslk** [comment]
What is the expected date to merge PR #549?

**Comment by joseaquino** [comment]
Friendly bump on this request, it would definitely bring more flexibility to the CQRS handlers and the PR looks to be working great 😀  any possibility of merging it in @kamilmysliwiec?

**Comment by k-jarzyna** [comment]
@kamilmysliwiec are there any plans to merge this branch into release?

**Comment by flashpaper12** [comment]
Bump! This would be fantastic if it could be merged!

**Comment by renanz** [comment]
Bump! This is a really helpful feature.

**Comment by skript53** [comment]
Bump! This would be very good!

**Comment by unckleg** [comment]
Bump!

**Comment by unckleg** [comment]
The bump I've posted 2+ years ago above was due to same challenge I've had earlier. **Multi-Teancy** + **Dynamic DB Runtime Connecting** (Implementing Nats Microservices based on CQRS + Messaging Broker + MongoDB)

We managed to overcome these limitations by monkey-patching here and there some stuff to make Nest.js DI Container happy, path of implementation was far from easy but we came with an "Elegant solution". 

Must mention digging into Nest.js internals/core we released bunch of hacks, kind of dirty implementations that we/you cannot see when you are just Consumer of the framework, suggesting for those who are interested and have time to go through the Nest.js core codebase 🗡️ 

That being said, I'm posting some bullet-points how we plumbed up everything to work with CQRS.
- Scope.Request we don't use it anywhere nor we can, nor we will in the future since we don't wont to trade App performance for our goal because of poor IoC implementation and app behaviour under the hood.
- We came up with using/implementing our global interceptor for all microservices that Intercepts consumer Nats.io events
   - There we are using node [async-hooks](https://nodejs.org/api/async_hooks.html) for context setting/switching (tenant-id, requestId) 
   - Created our "DBConnectionManager" that is retrieving tenant-id and connecting tenant to database if one is not already  being established by the same.
   - Monkey-patched all dependencies that are using Nest.js InjectModel decorator/method in our Query/Command handlers in how we called it "TenantAwareModule" by providing mock Models as Nest.js providers so we can bypass STATIC flagged modules and their IoC/DI during compile-time. Now we have mocks that are nothing than pure [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) classes that are calling our DBConnectionManager to retrieve model/connection during runtime (Nats.io message retrieved/interceptor) by fetching data from [async-hooks](https://nodejs.org/api/async_hooks.html) context mentioned above.

You can get inspiration from here [nestjs-context-poc](https://github.com/Hexenon/nestjs-context-poc/tree/e010e4e1c60eafcd938825345f750fdd780f5c76)

Will post more info about our findings.

And for the now we are not planning to use CQRS + DI Scope.Request feature once there is one in Nest.js cor. Why?  
My answer to that is that performance of application when you have hundreds of command/handlers would be terrible, also I'm sure that implementation for the issue above and proposed solutions will never arrive in that shape because core team is aware of what I've mentioned as performance issues above, and that's why for 2+ years there has been no solution to this.

**Comment by xdave** [comment]
@unckleg this may interest you https://github.com/xdave/nest-request-context

**Comment by unckleg** [comment]
@xdave Hi 👋

If you read my comment carefully you will se that we ended up with the same solution as in your repo: 

"As a solution, this uses node's AsyncLocalStorage from async_hooks to wrap the class in a Proxy that allows you to set/get fields on the class that are scoped any way that you want. Generally speaking, you'll want it scoped to the current Request."

We are using cls-hooked 👀🙂

I'm just sorry for the lost time implementing and trying to get everything working, on the other hand there is satisfaction again because as I see we are on the same page.

**Comment by UncleVic** [comment]
Bump! @kamilmysliwiec

**Comment by redplane** [comment]
I think it should support scoped service.
Passing the request information to command & queries is not a good idea :(.

This issue is 2 years old :|

**Comment by 9hnd5** [comment]
Check it out https://www.npmjs.com/package/nestjs-mediator I hope this is suitable for you. This package support injection of any provider with a scope request.

**Comment by huuhoa0506** [comment]
@kamilmysliwiec ka
I hope this issue will be resolved soon. It is really helpful for everyone.

**Comment by koblaymerve** [comment]
Is there any update about this issue? Looks like there is a PR for it already. Could you please give us an update, on when the PR merge  @kamilmysliwiec ? 🙏🏽
